---

- name: Reset PHP OPcache
  command: "{{ php_opcache_reset_binary }} -connect {{ item }} -r \"{{ php_opcache_reset_code }}\""
  with_items: php_opcache_reset_sockets
  register: php_opcache_reset_result
  changed_when: php_opcache_reset_result.rc == 0 and php_opcache_reset_result.stdout == php_opcache_reset_message_success
  failed_when: php_opcache_reset_result.rc != 0 or (php_opcache_reset_result.stdout != php_opcache_reset_message_success and php_opcache_reset_result.stdout != php_opcache_reset_message_disabled)
